name: python-learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - ipython
  - ipywidgets
  - nbformat
  - jupyter_client
  - notebook
  - sqlalchemy
  - pip
  - pip:
    - debugpy
    - faker
    - psycopg2-binary
    - pymongo
    - redis
    - neo4j
    - faker
    - plotly
    - nbconvert
